In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,10)   

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(100 , int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.ones ((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.zeros((2,5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
#### Create an array of zeros with 2 rows and 10 columns

np.zeros ((2,10) , int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [17]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
import numpy as np 

In [20]:
np.random.rand(3,2)

array([[0.10393838, 0.11155213],
       [0.44822145, 0.38312104],
       [0.40931777, 0.20811752]])

In [21]:
np.random.randn(3,2)

array([[-1.12097685, -1.5452864 ],
       [-1.77420401, -0.82266639],
       [ 0.4924754 ,  1.26011945]])

In [24]:
np.random.randint(34,100)

75

In [22]:
np.random.randint(20,56,100)

array([32, 24, 34, 39, 32, 27, 51, 43, 23, 24, 43, 22, 22, 45, 31, 26, 51,
       32, 51, 22, 50, 32, 23, 49, 53, 35, 25, 24, 38, 35, 48, 49, 55, 22,
       45, 39, 49, 20, 22, 51, 49, 23, 47, 35, 47, 40, 22, 46, 52, 22, 24,
       30, 52, 53, 44, 45, 21, 49, 25, 50, 35, 31, 37, 43, 25, 30, 37, 54,
       34, 27, 20, 42, 49, 54, 49, 22, 31, 25, 51, 55, 42, 33, 26, 48, 34,
       26, 34, 47, 37, 47, 52, 43, 20, 28, 37, 43, 28, 33, 38, 48])

In [23]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
rand_array=np.random.randint(0,100,20)
rand_array

array([79, 44, 12, 42, 28, 55, 60, 68, 18, 33, 67, 78, 43, 72, 45, 81, 89,
        8, 39, 58])

In [25]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
sample_array.reshape(3,7)

ValueError: ignored

In [27]:
rand_array.min()

8

In [28]:
rand_array.argmin()

17

In [29]:
rand_array.max()

89

In [30]:
rand_array.argmax()

16

In [31]:
sample_array.dtype

dtype('int64')

In [32]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
a=np.random.rand(2,3)
a

array([[0.05765528, 0.63465741, 0.16441495],
       [0.78467963, 0.84789016, 0.07440639]])

In [35]:
a.T

array([[0.05765528, 0.78467963],
       [0.63465741, 0.84789016],
       [0.16441495, 0.07440639]])

In [36]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
sample_array[-3]

18

In [38]:
sample_array[3:7]

array([13, 14, 15, 16])

In [39]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [40]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [42]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [43]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [44]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [45]:
### TWO DIMESIONAL ARRAY
import numpy as np

In [46]:
sample_matrix = np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [47]:
sample_matrix[1][2]

21

In [48]:
sample_matrix[0][2]

1

In [49]:
sample_matrix[2, :]

array([56, 76, 24,  7])

In [50]:
sample_matrix[2]

array([56, 76, 24,  7])

In [51]:
sample_matrix[: , (3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [52]:
### selection techniques


In [53]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [54]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [55]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [56]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [57]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [58]:
np.max(sample_array)

19

In [59]:
np.min(sample_array)

1

In [60]:
np.argmax(sample_array)

18

In [61]:
np.argmin(sample_array)

0

In [62]:
np.square (sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [63]:
np.std(sample_array)

5.477225575051661

In [64]:
np.var(sample_array)

30.0

In [65]:
np.mean(sample_array)

10.0

In [66]:
array=np.random.randn(3,4)
array

array([[ 0.81046564, -0.15074254,  0.40144712, -0.45253365],
       [ 1.0822528 , -0.76559014, -1.13889109,  1.33607836],
       [-0.94192728, -0.04621559,  0.77429434, -0.75792526]])

In [67]:
np.round(array , decimals=4)

array([[ 0.8105, -0.1507,  0.4014, -0.4525],
       [ 1.0823, -0.7656, -1.1389,  1.3361],
       [-0.9419, -0.0462,  0.7743, -0.7579]])

In [68]:
sports=np.array(['golf','cricket','football','fball'])
np.unique(sports)

array(['cricket', 'fball', 'football', 'golf'], dtype='<U8')